export type ReportItem = {
  id: string;
  title: string;
  description: string;
  type: string;
  exportTypes: Array<"PDF" | "Excel">;
  adminOnly?: boolean;
  lecturerOnly?: boolean;
  studentOnly?: boolean;
  requireSignature?: boolean;
};

export const REPORT_ITEMS: ReportItem[] = [
  {
    id: "r1",
    title: "Laporan Transkrip Wawancara",
    description: "Dokumen log percakapan lengkap sesi interview.",
    type: "transcript",
    exportTypes: ["PDF", "Excel"],
    studentOnly: true,
    requireSignature: true,
  },
  {
    id: "r2",
    title: "Laporan Hasil Evaluasi Skor (Performa Keseluruhan)",
    description: "Rekap nilai akhir per sesi latihan secara resmi.",
    type: "score-evaluation",
    exportTypes: ["PDF", "Excel"],
    requireSignature: true,
  },
  {
    id: "r3",
    title: "Laporan Analisis Kekuatan & Kelemahan",
    description: "Rincian kekuatan dan area perbaikan jawaban.",
    type: "strength-weakness",
    exportTypes: ["PDF", "Excel"],
    studentOnly: true,
    requireSignature: true,
  },
  {
    id: "r4",
    title: "Laporan Perbandingan Jawaban",
    description: "Tabel jawaban user versus jawaban ideal.",
    type: "answer-comparison",
    exportTypes: ["PDF", "Excel"],
    studentOnly: true,
    requireSignature: true,
  },
  {
    id: "r5",
    title: "Laporan Grafik Perkembangan",
    description: "Tren skor latihan dari waktu ke waktu.",
    type: "progress-chart",
    exportTypes: ["PDF", "Excel"],
    studentOnly: true,
    requireSignature: true,
  },
  {
    id: "r6",
    title: "Laporan Rekomendasi Pengembangan Diri",
    description: "Saran belajar dan latihan yang dipersonalisasi AI.",
    type: "development-recommendation",
    exportTypes: ["PDF", "Excel"],
    studentOnly: true,
    requireSignature: true,
  },
  {
    id: "r7",
    title: "Laporan Data Peserta Aktif & Demografi (Admin)",
    description: "Rekap resmi peserta yang aktif berlatih di platform.",
    type: "active-participants",
    exportTypes: ["PDF", "Excel"],
    adminOnly: true,
    requireSignature: true,
  },
  {
    id: "r8",
    title: "Laporan Analitik Modul (Admin)",
    description: "Data penggunaan dan kompetensi modul latihan.",
    type: "module-statistics",
    exportTypes: ["PDF", "Excel"],
    adminOnly: true,
    requireSignature: true,
  },
  {
    id: "r9",
    title: "Laporan Analisis Tingkat Kesulitan (Admin)",
    description: "Statistik soal yang paling sering dijawab salah.",
    type: "difficulty-analysis",
    exportTypes: ["PDF", "Excel"],
    adminOnly: true,
    requireSignature: true,
  },
  {
    id: "r10",
    title: "Sertifikat Latihan",
    description: "Bukti menyelesaikan sesi latihan interview.",
    type: "certificate",
    exportTypes: ["PDF"],
    studentOnly: true,
    requireSignature: false,
  },
  {
    id: "r11",
    title: "Laporan Statistik Penggunaan Sistem",
    description: "Jumlah sesi per periode, waktu latihan rata-rata, fitur yang paling sering digunakan.",
    type: "system-stats",
    exportTypes: ["PDF", "Excel"],
    adminOnly: true,
    requireSignature: true,
  },
  {
    id: "r12",
    title: "Laporan Feedback Pengguna",
    description: "Umpan balik dan penilaian sistem dari mahasiswa.",
    type: "user-feedback",
    exportTypes: ["PDF", "Excel"],
    adminOnly: true,
    requireSignature: true,
  },
  {
    id: "r13",
    title: "Laporan Penggunaan Bank Soal & Modul",
    description: "Rekap frekuensi penggunaan setiap butir bank soal oleh mahasiswa pada sesi latihan.",
    type: "question-bank-usage",
    exportTypes: ["PDF", "Excel"],
    lecturerOnly: true,
    requireSignature: true,
  },
  {
    id: "r14",
    title: "Laporan Akumulasi Kompetensi Mahasiswa",
    description: "Rekap rata-rata skor latihan mahasiswa berdasarkan kategori modul wawancara.",
    type: "student-competency-summary",
    exportTypes: ["PDF", "Excel"],
    lecturerOnly: true,
    requireSignature: true,
  },
  {
    id: "r15",
    title: "Laporan Analisis Kesalahan & Area Perbaikan Kelas",
    description: "Rangkuman indikator kriteria yang paling sering mendapat skor rendah oleh mahasiswa.",
    type: "class-error-analysis",
    exportTypes: ["PDF", "Excel"],
    lecturerOnly: true,
    requireSignature: true,
  },
  {
    id: "r16",
    title: "Laporan Evaluasi Kesulitan Soal",
    description: "Statistik sebaran nilai mahasiswa pada soal tingkat Mudah, Sedang, dan Sulit.",
    type: "question-difficulty-evaluation",
    exportTypes: ["PDF", "Excel"],
    lecturerOnly: true,
    requireSignature: true,
  },
  {
    id: "r17",
    title: "Laporan Keaktifan & Frekuensi Latihan Mahasiswa",
    description: "Log aktivitas sesi wawancara mahasiswa dan intensitas latihan dari waktu ke waktu.",
    type: "student-practice-attendance",
    exportTypes: ["PDF", "Excel"],
    lecturerOnly: true,
    requireSignature: true,
  },
  {
    id: "r18",
    title: "Laporan Rekapitulasi Bimbingan Dosen",
    description: "Laporan resmi kemajuan dan hasil pembimbingan wawancara kerja mahasiswa didik.",
    type: "lecturer-mentoring-summary",
    exportTypes: ["PDF", "Excel"],
    lecturerOnly: true,
    requireSignature: true,
  },
];
